[package]
name = "stbl-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pallet-evm = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
sp-io = { workspace = true }
ethereum = { workspace = true }
fp-ethereum = { workspace = true }
sha3 = { version = "0.10.6", default-features = false }
hex = { workspace= true, default-features = false }

[dev-dependencies]
pallet-evm = { workspace = true, features = ["std"] }
