[package]
name = "precompile-fee-token-selector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
num_enum = { version = "0.5.3", default-features = false }
paste = "1.0.6"
slices = "0.2.0"


precompile-utils = { workspace = true }

# Substrate
parity-scale-codec = { workspace = true, default-features = false, features = [
	"max-encoded-len",
] }
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-balances = { workspace = true }
pallet-timestamp = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-std = { workspace = true }
sp-runtime = { workspace = true }

# Frontier
fp-evm = { workspace = true }
pallet-evm = { workspace = true, features = ["forbid-evm-reentrancy"] }

pallet-user-fee-selector = { workspace = true }
pallet-validator-fee-selector = { workspace = true }
pallet-supported-tokens-manager = { workspace = true }
pallet-erc20-manager = { workspace = true }

[dev-dependencies]
fc-rpc = { workspace = true }
derive_more = { version = "0.99" }
hex-literal = "0.3.4"
libsecp256k1 = "0.7"
serde = { version = "1.0.100" }
sha3 = "0.10"

precompile-utils = { workspace = true, features = ["testing"] }

pallet-timestamp = { workspace = true }
scale-info = { version = "2.0", default-features = false, features = [
	"derive",
] }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = [
	"fp-evm/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-evm/std",
	"parity-scale-codec/std",
	"precompile-utils/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
