[package]
name = "stbl-core-primitives"
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.1"

[dependencies]
account = { workspace = true, default-features = false }
parity-scale-codec = { workspace = true, default-features = false, features = ["derive"] }
fp-self-contained = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-application-crypto = { workspace = true, default-features = false }
scale-info = { workspace = true, default-features = false }

[features]
default = [ "std" ]
std = [
	"account/std",
	"fp-self-contained/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-runtime/std",
]
