[package]
name = "pallet-user-fee-selector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
pallet-supported-tokens-manager = { workspace = true }
pallet-erc20-manager = { workspace = true }

[dev-dependencies]
pallet-timestamp = { workspace = true }
pallet-balances = { workspace = true, features = ["std"] }
staging-xcm = { workspace = true }

[features]
default = ["std"]
std = [
	"frame-support/std",
	"frame-system/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-std/std",
	'staging-xcm/std',
]
