[package]
name = "stbl-transaction-validator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fp-ethereum = { workspace = true, default-features = false }
fp-evm = { workspace = true, default-features = false }
pallet-evm = { workspace = true, default-features = false }
pallet-ethereum = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-runtime = { features = ["serde"], workspace = true }
sp-std = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
ethereum = { workspace = true, default-features = false }
sha3 = { version = "0.10.6", default-features = false }
frame-system = { workspace = true, default-features = false }
pallet-user-fee-selector = { workspace = true, default-features = false }
stbl-tools = { workspace = true }
environmental = { workspace = true, optional = true }
frame-support = { workspace = true }
evm = { workspace = true, features = ["with-codec"] }
codec = { workspace = true, features = ["derive"] }
scale-info = { features = ["derive", "serde"], workspace = true }
serde = { features = ["alloc", "derive"], workspace = true }
frame-benchmarking = { workspace = true, optional = true }
log = { workspace = true }
pallet-timestamp = { workspace = true }
precompile-utils = { workspace = true }

[dev-dependencies]
frame-support = { workspace = true }
frame-system = { workspace = true }
hex = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-balances = { workspace = true, features = ["std"] }
pallet-evm = { workspace = true, features = ["std"] }
pallet-ethereum = { workspace = true, features = ["std"] }
pallet-supported-tokens-manager = { workspace = true }
pallet-erc20-manager = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = ['frame-benchmarking']
std = [
	"environmental?/std",
	"evm/std",
	"evm/with-serde",
	"fp-evm/std",
	'frame-benchmarking/std',
	"frame-support/std",
	"frame-system/std",
	"pallet-evm/std",
	"pallet-timestamp/std",
	"pallet-user-fee-selector/std",
	"codec/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"precompile-utils/std",
]
forbid-evm-reentrancy = ["dep:environmental"]
try-runtime = ['frame-support/try-runtime']
