name: Cargo Test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  IMAGE_NAME: stability-test
  REGISTRY: ghcr.io
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: $
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image for testing
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./docker/test/Dockerfile
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{env.IMAGE_NAME}}:${{github.sha}}
      - name: Run tests
        run: docker run ${{env.IMAGE_NAME}}:${{github.sha}}
