name: Cargo Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  IMAGE_NAME: stability-test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build docker image for testing
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./docker/test/Dockerfile
          push: false
          tags: ${{env.IMAGE_NAME}}:${{github.sha}}
      - name: Run tests
        run: docker run ${{env.IMAGE_NAME}}:${{github.sha}}
