[package]
name = "stability-rpc-api"
version = "0.1.0"
edition = "2021"

[dependencies]
fp-ethereum = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-api = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
codec = { workspace = true }

[features]
default = [ "std" ]
std = [ 'codec/std', 'sp-api/std', 'sp-core/std', 'sp-std/std' ]
